version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/chandruproj
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  AfterInstall:
    - location: post_install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: run.sh
      timeout: 120
      runas: ubuntu